In [11]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [12]:
datos_csv = pd.read_csv("../Datos_brutos/bank-additional.csv")

datos_csv.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [13]:
datos_excel = pd.read_excel('../Datos_brutos/customer-details.xlsx', sheet_name=None)

datos_excel

{'2012':        Unnamed: 0  Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
 0               0  161770        1         0  2012-04-04                 29
 1               1   85477        1         1  2012-12-30                  7
 2               2  147233        1         1  2012-02-02                  5
 3               3  121393        1         2  2012-12-21                 29
 4               4   63164        1         2  2012-06-20                 20
 ...           ...     ...      ...       ...         ...                ...
 20110       20110  114469        0         2  2012-10-28                 13
 20111       20111   82207        0         1  2012-02-10                 27
 20112       20112  135009        0         0  2012-09-14                 17
 20113       20113    8486        1         1  2012-07-04                 18
 20114       20114  144419        1         0  2012-04-12                 29

                                          ID
 0      089b39d8-e4d0-461b-87d4-814d71e0e079
 1      e9d37224-cb6f-4942-98d7-46672963d097
 2      3f9f49b5-e410-4948-bf6e-f9244f04918b
 3      9991fafb-4447-451a-8be2-b0df6098d13e
 4      eca60b76-70b6-4077-80ba-bc52e8ebb0eb
 ...                                     ...
 20110  25f35a3f-0fd2-4e6a-b4d5-74fa1a1f4cfc
 20111  a3d2d088-3781-44ea-9944-a4a40df51285
 20112  3769cb72-26be-40f2-9a93-f752fc96d628
 20113  d507f6b3-a030-46d7-9615-61fe3f6b8028
 20114  8299f0a6-e4c0-49fc-87ab-81308b70f80f

 [20115 rows x 7 columns],
 '2013':       Unnamed: 0  Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
 0              0   82407        0         1  2013-10-07                 29
 1              1   24877        0         0  2013-04-21                 32
 2              2   78839        1         0  2013-11-25                 21
 3              3  113859        1         1  2013-01-06                 12
 4              4  147317        0         0  2013-07-10                 14
 ...          ...     ...      ...       ...         ...                ...
 8960        8960  139839        0         0  2013-12-10                  8
 8961        8961   65516        0         2  2013-10-01                 26
 8962        8962   56664        1         0  2013-12-07                 13
 8963        8963   25089        0         1  2013-08-24                 14
 8964        8964   77504        0         0  2013-06-30                  6

                                         ID
 0     ef81336c-e41a-46d0-8a30-5d4ac3b836be
 1     50b224ac-84b4-42a7-aba9-3e1d1d620479
 2     9cb15c53-b647-464a-add9-09cdae04897c
 3     f8aaf334-949d-4943-a214-b64fe9c088b4
 4     885fe85a-3718-4760-a32a-a57628cf7528
 ...                                    ...
 8960  6f7a03ac-c1b9-4acf-a28b-37cc8254a92e
 8961  ed489dce-7ccf-46ad-a0d4-bb71c566fa40
 8962  01b3ac53-b1bd-450a-be11-6893b3aeadd5
 8963  8906c203-a13f-4b10-985c-bd72bd01a011
 8964  ba7fb638-c6cb-4dc8-aad4-75456c3818c5

 [8965 rows x 7 columns],
 '2014':        Unnamed: 0  Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
 0               0  168812        1         1  2014-06-10                 27
 1               1  108615        2         1  2014-04-05                 24
 2               2  179041        0         2  2014-09-22                  4
 3               3  116639        2         2  2014-08-16                  3
 4               4   49537        0         1  2014-09-05                 28
 ...           ...     ...      ...       ...         ...                ...
 14085       14085  156980        1         2  2014-05-17                  7
 14086       14086  139820        0         0  2014-09-29                  1
 14087       14087   78470        2         2  2014-10-28                 12
 14088       14088  144218        0         1  2014-07-01                  9
 14089       14089  115155        0         2  2014-12-25                  7

                                          ID
 0      4d6c811c-0f24-4a73-b374-2ebd1f80d46e
 1      eef0f24f-cbdb-4c67-b371-09d7bc59695e
 2      bbfdcedd-199d-4927-94bb-5dad051ff471
 3      e8ebb67d-4ee1-4615-b701-eefe3af607eb
 4      f7f79ace-0024-4505-a401-f340946f0942
 ...                                     ...
 14085  5f432048-d515-4bb5-9c94-62db451f88d4
 14086  993bbbd6-4dbc-4a40-a408-f91f8462bee6
 14087  d6271666-319d-42c8-a741-cb22bf2c2093
 14088  f67fbfa8-6573-414d-a805-b26a2f1b1ceb
 14089  9727bc06-c11a-461a-a5bb-3d210467cc2a

 [14090 rows x 7 columns]}

In [14]:
datos_excel = pd.concat(datos_excel.values(), ignore_index=True) # Se concatenan la hojas en un solo dataframe.
datos_excel.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [15]:
df1 = datos_csv
df2 = datos_excel

In [16]:
df1.columns

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='str')

In [17]:
# Creamos un diccionario para traducir los encabezados de las columnas.

traducciones = {
    'age': 'edad',
    'job': 'ocupacion',
    'marital': 'estado_civil',
    'education': 'nivel_educativo',
    'default': 'historial_incumplimiento',
    'housing': 'prestamo_hipotecario',
    'loan': 'otro_prestamo',
    'contact': 'metodo_contacto',
    'duration': 'duracion_ultima_interaccion',
    'campaign': 'contactos_en_campaña',
    'pdays': 'dias_ultimo_contacto',
    'previous': 'contactos_previos',
    'poutcome': 'resultado_campaña_previa',
    'emp.var.rate': 'tasa_variacion_empleo',
    'cons.price.idx': 'indice_precios_consumidor',
    'cons.conf.idx': 'indice_confianza_consumidor',
    'euribor3m': 'tasa_interes_3m',
    'nr.employed': 'numero_empleados',
    'y': 'suscripcion_producto',
    'date': 'fecha_interaccion',
    'contact_month': 'mes_contacto',
    'contact_year': 'año_contacto',
    'id_': 'id'
}

In [18]:
df2.columns

Index(['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer',
       'NumWebVisitsMonth', 'ID'],
      dtype='str')

In [19]:
traducciones_2 = {
    'Unnamed: 0': 'indice_original',
    'Income': 'ingreso_anual',
    'Kidhome': 'num_niños',
    'Teenhome': 'num_adolescentes',
    'Dt_Customer': 'fecha_alta_cliente',
    'NumWebVisitsMonth': 'visitas_web_mensuales',
    'ID': 'id'
}

In [20]:
df1 = df1.rename(columns=traducciones)

In [21]:
df2 = df2.rename(columns=traducciones_2)

In [22]:
df1.head()

,Unnamed: 0,edad,ocupacion,estado_civil,nivel_educativo,historial_incumplimiento,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,id
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [23]:
df2.head()

,indice_original,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales,id
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [24]:
# Vemos si todos los id son unicos
print(df1['id'].is_unique)
print(df2['id'].is_unique)

# Vemos si coinciden en los dos dataframes
coinciden = set(df1['id']).intersection(df2['id'])
print(len(coinciden))

# vemos los id que estan solo en un dataframe
solo_df1 = set(df1['id']) - set(df2['id'])
solo_df2 = set(df2['id']) - set(df1['id'])

print("IDs solo en df1:", len(solo_df1))
print("IDs solo en df2:", len(solo_df2))

True
True
43000
IDs solo en df1: 0
IDs solo en df2: 170

In [25]:
# Los unimos descartando los que solo estan en el dataframe de caracteristicas demograficas.

df = df1.merge(df2, on="id", how="inner")
df.head()

,Unnamed: 0,edad,ocupacion,estado_civil,nivel_educativo,historial_incumplimiento,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,id,indice_original,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,0,161770,1,0,2012-04-04,29
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,1,85477,1,1,2012-12-30,7
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,2,147233,1,1,2012-02-02,5
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,3,121393,1,2,2012-12-21,29
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,4,63164,1,2,2012-06-20,20

In [26]:
df=df.set_index('id') # Ponemos el id como indice
df.head()

,Unnamed: 0,edad,ocupacion,estado_civil,nivel_educativo,historial_incumplimiento,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,indice_original,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,0,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,1,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,2,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,3,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,4,63164,1,2,2012-06-20,20

In [27]:
df= df.drop(columns=['Unnamed: 0'])  #Eliminamos la columna
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,historial_incumplimiento,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,indice_original,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,0,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,1,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,2,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,3,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,4,63164,1,2,2012-06-20,20

In [28]:
df=df.drop(columns=['indice_original'])
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,historial_incumplimiento,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,63164,1,2,2012-06-20,20

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 43000 entries, 089b39d8-e4d0-461b-87d4-814d71e0e079 to 993bbbd6-4dbc-4a40-a408-f91f8462bee6
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   edad                         37880 non-null  float64
 1   ocupacion                    42655 non-null  str
 2   estado_civil                 42915 non-null  str
 3   nivel_educativo              41193 non-null  str
 4   historial_incumplimiento     34019 non-null  float64
 5   prestamo_hipotecario         41974 non-null  float64
 6   otro_prestamo                41974 non-null  float64
 7   metodo_contacto              43000 non-null  str
 8   duracion_ultima_interaccion  43000 non-null  int64
 9   contactos_en_campaña         43000 non-null  int64
 10  dias_ultimo_contacto         43000 non-null  int64
 11  contactos_previos            43000 non-null  int64
 12  resultado_campaña_previa     43000 non-null  str
 13  tasa_variacion_empleo        43000 non-null  float64
 14  indice_precios_consumidor    42529 non-null  str
 15  indice_confianza_consumidor  43000 non-null  str
 16  tasa_interes_3m              33744 non-null  str
 17  numero_empleados             43000 non-null  str
 18  suscripcion_producto         43000 non-null  str
 19  fecha_interaccion            42752 non-null  str
 20  latitude                     43000 non-null  float64
 21  longitude                    43000 non-null  float64
 22  ingreso_anual                43000 non-null  int64
 23  num_niños                    43000 non-null  int64
 24  num_adolescentes             43000 non-null  int64
 25  fecha_alta_cliente           43000 non-null  datetime64[us]
 26  visitas_web_mensuales        43000 non-null  int64
dtypes: datetime64[us](1), float64(7), int64(8), str(11)
memory usage: 9.2+ MB

In [30]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
edad,37880.0,39.977112,17.0,32.0,38.0,47.0,98.0,10.437957
historial_incumplimiento,34019.0,0.000088,0.0,0.0,0.0,0.0,1.0,0.00939
prestamo_hipotecario,41974.0,0.535998,0.0,0.0,1.0,1.0,1.0,0.498708
otro_prestamo,41974.0,0.15562,0.0,0.0,0.0,0.0,1.0,0.362499
duracion_ultima_interaccion,43000.0,257.739279,0.0,102.0,179.0,319.0,4918.0,258.666033
contactos_en_campaña,43000.0,2.567233,1.0,1.0,2.0,3.0,56.0,2.772294
dias_ultimo_contacto,43000.0,962.330953,0.0,999.0,999.0,999.0,999.0,187.260394
contactos_previos,43000.0,0.174023,0.0,0.0,0.0,0.0,7.0,0.497366
tasa_variacion_empleo,43000.0,0.077128,-3.4,-1.8,1.1,1.4,1.4,1.573898
latitude,43000.0,36.856697,24.396,30.61475,36.761,43.11325,49.384,7.225948
longitude,43000.0,-95.939067,-124.997,-110.49425,-95.8995,-81.42775,-66.937,16.752282
ingreso_anual,43000.0,93241.20007,5841.0,49610.0,93050.5,136744.5,180802.0,50498.316182
num_niños,43000.0,1.004791,0.0,0.0,1.0,2.0,2.0,0.815913
num_adolescentes,43000.0,0.998605,0.0,0.0,1.0,2.0,2.0,0.815983
fecha_alta_cliente,43000,2013-05-12 07:05:06.083721,2012-01-01 00:00:00,2012-07-16 00:00:00,2013-03-02 00:00:00,2014-03-29 00:00:00,2014-12-31 00:00:00,NaN
visitas_web_mensuales,43000.0,16.589698,1.0,9.0,17.0,25.0,32.0,9.239205

In [31]:
df.describe(include=str).T

                             count unique                top   freq
ocupacion                    42655     11             admin.  10873
estado_civil                 42915      3            MARRIED  25999
nivel_educativo              41193      7  university.degree  12722
metodo_contacto              43000      2           cellular  27396
resultado_campaña_previa     43000      3        NONEXISTENT  37103
indice_precios_consumidor    42529     26             93,994   7938
indice_confianza_consumidor  43000     26              -36,4   8020
tasa_interes_3m              33744    309              4,857   2287
numero_empleados             43000     11             5228,1  16980
suscripcion_producto         43000      2                 no  38156
fecha_interaccion            42752   1825    28-febrero-2018     95

In [32]:
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,historial_incumplimiento,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,63164,1,2,2012-06-20,20

In [33]:
df.dtypes

edad                                  float64
ocupacion                                 str
estado_civil                              str
nivel_educativo                           str
historial_incumplimiento              float64
prestamo_hipotecario                  float64
otro_prestamo                         float64
metodo_contacto                           str
duracion_ultima_interaccion             int64
contactos_en_campaña                    int64
dias_ultimo_contacto                    int64
contactos_previos                       int64
resultado_campaña_previa                  str
tasa_variacion_empleo                 float64
indice_precios_consumidor                 str
indice_confianza_consumidor               str
tasa_interes_3m                           str
numero_empleados                          str
suscripcion_producto                      str
fecha_interaccion                         str
latitude                              float64
longitude                             float64
ingreso_anual                           int64
num_niños                               int64
num_adolescentes                        int64
fecha_alta_cliente             datetime64[us]
visitas_web_mensuales                   int64
dtype: object

In [34]:
df['edad'].value_counts()

edad
31.0    1810
33.0    1704
32.0    1672
36.0    1649
34.0    1608
        ...
98.0       2
89.0       2
95.0       1
87.0       1
94.0       1
Name: count, Length: 78, dtype: int64

In [35]:
df['ocupacion'].value_counts()

ocupacion
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
Name: count, dtype: int64

In [36]:
df['estado_civil'].value_counts()

estado_civil
MARRIED     25999
SINGLE      12105
DIVORCED     4811
Name: count, dtype: int64

In [37]:
df['nivel_educativo'].value_counts()

nivel_educativo
university.degree      12722
high.school             9925
basic.9y                6309
professional.course     5477
basic.4y                4356
basic.6y                2386
illiterate                18
Name: count, dtype: int64

In [38]:
df['historial_incumplimiento'].value_counts() # Solo hay 3 valores positivos. Se elimina la columna.

historial_incumplimiento
0.0    34016
1.0        3
Name: count, dtype: int64

In [39]:
df= df.drop(columns=['historial_incumplimiento'])
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,63164,1,2,2012-06-20,20

In [151]:
df['prestamo_hipotecario'].value_counts()

prestamo_hipotecario
1.0    22498
0.0    19476
Name: count, dtype: int64

In [44]:
df['prestamo_hipotecario'].value_counts(dropna=False)

prestamo_hipotecario
1.0    22498
0.0    19476
NaN     1026
Name: count, dtype: int64

In [ ]:
df['prestamo_hipotecario']=df['prestamo_hipotecario'].map({1.0: True, 0.0:False}) # Se combierte en booleano

In [47]:
df['prestamo_hipotecario'].value_counts(dropna=False)

prestamo_hipotecario
True     22498
False    19476
NaN       1026
Name: count, dtype: int64

In [154]:
df['otro_prestamo'].value_counts()

otro_prestamo
0.0    35442
1.0     6532
Name: count, dtype: int64

In [48]:
df['otro_prestamo'].value_counts(dropna=False)

otro_prestamo
0.0    35442
1.0     6532
NaN     1026
Name: count, dtype: int64

In [49]:
df['otro_prestamo']=df['otro_prestamo'].map({1.0: True, 0.0:False}) # Se combierte en booleano

In [51]:
df['otro_prestamo'].value_counts(dropna=False)

otro_prestamo
False    35442
True      6532
NaN       1026
Name: count, dtype: int64

In [52]:
df['metodo_contacto'].value_counts()

metodo_contacto
cellular     27396
telephone    15604
Name: count, dtype: int64

In [53]:
df['duracion_ultima_interaccion'].value_counts()

duracion_ultima_interaccion
90      183
136     177
85      177
73      172
111     170
       ...
1640      1
1616      1
1246      1
1556      1
1868      1
Name: count, Length: 1540, dtype: int64

In [54]:
df['duracion_ultima_interaccion'].describe()

count    43000.000000
mean       257.739279
std        258.666033
min          0.000000
25%        102.000000
50%        179.000000
75%        319.000000
max       4918.000000
Name: duracion_ultima_interaccion, dtype: float64

In [55]:
df['contactos_en_campaña'].value_counts()

contactos_en_campaña
1     18404
2     11048
3      5584
4      2777
5      1658
6      1025
7       658
8       418
9       289
10      236
11      183
12      130
13       94
14       73
17       61
16       51
15       51
18       34
20       30
19       26
21       26
23       20
24       18
22       17
27       11
29       10
30       10
25        8
28        8
26        8
31        8
35        5
32        4
33        4
34        3
42        2
40        2
43        2
56        1
39        1
41        1
37        1
Name: count, dtype: int64

In [56]:
df['contactos_en_campaña'].describe()

count    43000.000000
mean         2.567233
std          2.772294
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         56.000000
Name: contactos_en_campaña, dtype: float64

In [57]:
df['dias_ultimo_contacto'].value_counts()

dias_ultimo_contacto
999    41412
3        457
6        428
4        121
9         67
7         66
2         63
12        61
10        55
5         50
13        38
11        30
1         26
15        26
14        22
8         20
0         15
16        13
17        10
18         7
22         4
19         3
21         2
25         1
26         1
27         1
20         1
Name: count, dtype: int64

In [58]:
df['dias_ultimo_contacto'] = df['dias_ultimo_contacto'].replace(999, np.nan) # Cambiamos el 999 por NaN

In [59]:
df['dias_ultimo_contacto'].value_counts()

dias_ultimo_contacto
3.0     457
6.0     428
4.0     121
9.0      67
7.0      66
2.0      63
12.0     61
10.0     55
5.0      50
13.0     38
11.0     30
1.0      26
15.0     26
14.0     22
8.0      20
0.0      15
16.0     13
17.0     10
18.0      7
22.0      4
19.0      3
21.0      2
25.0      1
26.0      1
27.0      1
20.0      1
Name: count, dtype: int64

In [60]:
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,False,False,telephone,261,1,NaN,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,False,False,telephone,149,1,NaN,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,True,False,telephone,226,1,NaN,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,False,False,telephone,151,1,NaN,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,False,True,telephone,307,1,NaN,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,63164,1,2,2012-06-20,20

In [61]:
df['contactos_previos'].value_counts()

contactos_previos
0    37103
1     4778
2      786
3      232
4       75
5       20
6        5
7        1
Name: count, dtype: int64

In [62]:
df['resultado_campaña_previa'].value_counts()

resultado_campaña_previa
NONEXISTENT    37103
FAILURE         4461
SUCCESS         1436
Name: count, dtype: int64

In [63]:
df['resultado_campaña_previa']=df['resultado_campaña_previa'].map({'SUCCESS': True, 'FAILURE':False, 'NONEXISTENT':np.nan})

In [64]:
df['resultado_campaña_previa'].value_counts()

resultado_campaña_previa
False    4461
True     1436
Name: count, dtype: int64

In [65]:
df['tasa_variacion_empleo'].value_counts()

tasa_variacion_empleo
 1.4    16980
-1.8     9620
 1.1     8020
-0.1     3830
-2.9     1748
-3.4     1133
-1.7      812
-1.1      665
-3.0      181
-0.2       11
Name: count, dtype: int64

In [66]:
df['indice_precios_consumidor'].value_counts()

indice_precios_consumidor
93,994    7938
93,918    6937
92,893    5985
93,444    5349
94,465    4522
93,2      3731
93,075    2552
92,201     803
92,963     742
92,431     471
92,649     375
94,215     320
94,199     316
92,843     298
92,379     274
93,369     271
94,027     242
94,055     236
93,876     224
94,601     212
92,469     184
92,713     179
93,749     179
94,767     130
93,798      48
92,756      11
Name: count, dtype: int64

In [67]:
df['indice_precios_consumidor'].dtype

In [68]:
df['indice_precios_consumidor'] = df['indice_precios_consumidor'].str.replace(',','.', regex=False) # Cambiamos las comas por puntos

In [69]:
df['indice_precios_consumidor'] = pd.to_numeric(df['indice_precios_consumidor'], errors='coerce') # Lo cambiamos a float

In [70]:
df['indice_precios_consumidor'].dtype

dtype('float64')

In [71]:
df['indice_precios_consumidor'].value_counts()

indice_precios_consumidor
93.994    7938
93.918    6937
92.893    5985
93.444    5349
94.465    4522
93.200    3731
93.075    2552
92.201     803
92.963     742
92.431     471
92.649     375
94.215     320
94.199     316
92.843     298
92.379     274
93.369     271
94.027     242
94.055     236
93.876     224
94.601     212
92.469     184
92.713     179
93.749     179
94.767     130
93.798      48
92.756      11
Name: count, dtype: int64

In [72]:
df['indice_confianza_consumidor'].value_counts()

indice_confianza_consumidor
-36,4    8020
-42,7    7004
-46,2    6057
-36,1    5408
-41,8    4568
-42      3782
-47,1    2581
-31,4     815
-40,8     748
-26,9     477
-30,1     379
-40,3     328
-37,5     318
-50       299
-29,8     277
-34,8     275
-38,3     245
-39,8     239
-40       225
-49,5     214
-33,6     185
-34,6     183
-33       181
-50,8     133
-40,4      48
-45,9      11
Name: count, dtype: int64

In [73]:
df['indice_confianza_consumidor'] = df['indice_confianza_consumidor'].str.replace(',','.', regex=False)

In [74]:
df['indice_confianza_consumidor'] = df['indice_confianza_consumidor'].astype(float) # lo cambiamos a float

In [75]:
df['indice_confianza_consumidor'].dtype

dtype('float64')

In [76]:
df['indice_confianza_consumidor'].value_counts()

indice_confianza_consumidor
-36.4    8020
-42.7    7004
-46.2    6057
-36.1    5408
-41.8    4568
-42.0    3782
-47.1    2581
-31.4     815
-40.8     748
-26.9     477
-30.1     379
-40.3     328
-37.5     318
-50.0     299
-29.8     277
-34.8     275
-38.3     245
-39.8     239
-40.0     225
-49.5     214
-33.6     185
-34.6     183
-33.0     181
-50.8     133
-40.4      48
-45.9      11
Name: count, dtype: int64

In [77]:
df['tasa_interes_3m'].value_counts()

tasa_interes_3m
4,857    2287
4,962    2124
4,963    2019
4,961    1594
4,964     964
         ...
0,895       1
0,894       1
0,953       1
0,956       1
1,047       1
Name: count, Length: 309, dtype: int64

In [78]:
df['tasa_interes_3m'] = df['tasa_interes_3m'].str.replace(',','.', regex=False)

In [79]:
df['tasa_interes_3m'] = df['tasa_interes_3m'].astype(float)

In [80]:
df['tasa_interes_3m'].value_counts()

tasa_interes_3m
4.857    2287
4.962    2124
4.963    2019
4.961    1594
4.964     964
         ...
0.895       1
0.894       1
0.953       1
0.956       1
1.047       1
Name: count, Length: 309, dtype: int64

In [81]:
df['numero_empleados'].value_counts()

numero_empleados
5228,1    16980
5099,1     8937
5191       8020
5195,8     3830
5076,2     1748
5017,5     1133
4991,6      812
5008,7      683
4963,6      665
5023,5      181
5176,3       11
Name: count, dtype: int64

In [82]:
df['numero_empleados'] = df['numero_empleados'].str.replace(',','.', regex=False)

In [83]:
df['numero_empleados'] = df['numero_empleados'].astype(float)

In [84]:
df['suscripcion_producto'].value_counts()

suscripcion_producto
no     38156
yes     4844
Name: count, dtype: int64

In [85]:
df['suscripcion_producto']=df['suscripcion_producto'].map({'yes': True, 'no':False})

In [86]:
df['suscripcion_producto'].value_counts()

suscripcion_producto
False    38156
True      4844
Name: count, dtype: int64

In [87]:
df['suscripcion_producto'].dtype

dtype('bool')

In [88]:
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,latitude,longitude,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,False,False,telephone,261,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2-agosto-2019,41.495,-71.233,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,False,False,telephone,149,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,14-septiembre-2016,34.601,-83.923,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,True,False,telephone,226,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,15-febrero-2019,34.939,-94.847,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,False,False,telephone,151,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,29-noviembre-2015,49.041,-70.308,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,False,True,telephone,307,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,29-enero-2017,38.033,-104.463,63164,1,2,2012-06-20,20

In [89]:
df['fecha_interaccion'].value_counts()

fecha_interaccion
28-febrero-2018      95
28-febrero-2016      94
28-febrero-2015      92
28-febrero-2017      89
28-febrero-2019      85
                     ..
16-enero-2019        11
21-diciembre-2019    10
20-noviembre-2015    10
4-abril-2017         10
14-abril-2015        10
Name: count, Length: 1825, dtype: int64

In [90]:
df['fecha_interaccion'].dtype

In [91]:
#Cambiamos el nombre del mes es español a numero para poder covertirlo en formato fecha

df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('enero', '01')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('febrero', '02')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('marzo', '03')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('abril', '04')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('mayo', '05')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('junio', '06')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('julio', '07')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('agosto', '08')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('septiembre', '09')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('octubre', '10')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('noviembre', '11')
df['fecha_interaccion'] = df['fecha_interaccion'].str.replace('diciembre', '12')

In [92]:
df['fecha_interaccion']= pd.to_datetime(df['fecha_interaccion'], dayfirst=True)

In [93]:
df['fecha_interaccion'].dtype

dtype('<M8[us]')

In [94]:
# Latitud y longitud las eliminamos

df= df.drop(columns=['latitude', 'longitude'])

In [95]:
df.head()

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales
id,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,False,False,telephone,261,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2019-08-02,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,False,False,telephone,149,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2016-09-14,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,True,False,telephone,226,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2019-02-15,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,False,False,telephone,151,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2015-11-29,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,False,True,telephone,307,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2017-01-29,63164,1,2,2012-06-20,20

In [96]:
df['ingreso_anual'].value_counts()

ingreso_anual
70422     5
40655     5
44944     4
170766    4
16284     4
         ..
68672     1
73578     1
9816      1
156980    1
139820    1
Name: count, Length: 38173, dtype: int64

In [97]:
df['ingreso_anual'].describe()

count     43000.000000
mean      93241.200070
std       50498.316182
min        5841.000000
25%       49610.000000
50%       93050.500000
75%      136744.500000
max      180802.000000
Name: ingreso_anual, dtype: float64

In [98]:
df['num_niños'].value_counts()

num_niños
2    14416
1    14374
0    14210
Name: count, dtype: int64

In [99]:
df['num_adolescentes'].value_counts()

num_adolescentes
1    14370
0    14345
2    14285
Name: count, dtype: int64

In [100]:
#Creamos la columna numero de hijos

df['num_hijos'] = df['num_niños'] + df['num_adolescentes']

In [101]:
df.sample(10)

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales,num_hijos
id,,,,,,,,,,,,,,,,,,,,,,,,,
8adad023-1654-4737-9eff-9dbc756f7329,26.0,admin.,SINGLE,university.degree,True,False,cellular,213,1,NaN,0,NaN,-2.9,92.963,-40.8,1.260,5076.2,False,2016-09-18,107904,2,1,2014-06-20,29,3
58694389-802b-4ec0-9f9a-355f8b69999d,33.0,self-employed,MARRIED,professional.course,True,False,telephone,141,4,NaN,0,NaN,1.4,94.465,-41.8,4.947,5228.1,False,2017-01-07,98305,1,2,2012-09-22,16,3
b3431961-e8a6-41e1-a1fb-e3e8fcd9d4d5,35.0,student,SINGLE,university.degree,True,True,telephone,217,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2016-04-23,15666,2,0,2012-02-11,17,2
1c2b650e-08e5-4886-b0fc-8803fd56e125,27.0,admin.,SINGLE,high.school,True,True,cellular,144,1,NaN,0,NaN,1.4,93.918,-42.7,4.962,5228.1,False,2015-06-01,79615,1,2,2012-06-17,23,3
e964fb9c-f91e-46fa-8bf1-a510e8ddf9d2,56.0,entrepreneur,MARRIED,university.degree,True,False,telephone,428,2,NaN,0,NaN,1.1,93.994,-36.4,4.859,5191.0,False,2018-12-22,81685,1,0,2012-07-11,10,1
1c3bcd93-720e-426f-a233-6d121e89b644,NaN,unemployed,SINGLE,high.school,True,False,telephone,142,3,NaN,0,NaN,1.4,94.465,-41.8,4.961,5228.1,False,2016-06-29,112726,0,0,2012-09-24,27,0
a74fc792-d484-4cd4-b5f6-0acd8fa697b9,37.0,blue-collar,MARRIED,basic.4y,False,True,telephone,280,2,NaN,0,NaN,1.1,93.994,-36.4,4.855,5191.0,False,2016-07-16,137990,0,2,2012-03-07,21,2
85de9d69-0d6f-4668-b63f-69001f383590,33.0,admin.,SINGLE,university.degree,True,True,telephone,117,1,NaN,0,NaN,-1.8,93.075,-47.1,1.415,5099.1,False,2016-04-05,32682,2,0,2013-12-19,27,2
cde15dbe-ae6f-4f3e-9b40-f58a254796a5,44.0,self-employed,MARRIED,basic.9y,False,False,cellular,136,10,NaN,0,NaN,1.4,93.444,-36.1,4.965,5228.1,False,2015-12-27,82560,0,1,2013-09-10,13,1
06c1f48e-b67f-4976-a18c-4ad7f0e36cc5,32.0,self-employed,MARRIED,university.degree,True,False,cellular,247,1,6.0,3,False,-3.4,92.649,-30.1,0.714,5017.5,True,2016-05-16,63795,0,0,2014-08-29,12,0

In [102]:
df['fecha_alta_cliente'].value_counts()

fecha_alta_cliente
2012-08-10    79
2012-01-11    79
2012-12-28    75
2012-12-21    72
2012-08-13    72
              ..
2013-09-03    15
2013-02-26    15
2013-06-05    15
2013-10-18    13
2013-10-24    12
Name: count, Length: 1096, dtype: int64

In [103]:
df['fecha_alta_cliente'].dtype

dtype('<M8[us]')

In [104]:
df['visitas_web_mensuales'].value_counts()

visitas_web_mensuales
14    1424
32    1407
3     1406
12    1390
21    1382
31    1382
29    1381
23    1367
20    1360
27    1357
15    1357
28    1356
13    1356
4     1356
10    1355
22    1349
26    1342
25    1338
19    1334
24    1331
9     1330
17    1326
5     1325
30    1322
8     1322
6     1321
1     1308
11    1299
16    1290
18    1281
7     1277
2     1269
Name: count, dtype: int64

In [105]:
df['visitas_web_mensuales'].describe()

count    43000.000000
mean        16.589698
std          9.239205
min          1.000000
25%          9.000000
50%         17.000000
75%         25.000000
max         32.000000
Name: visitas_web_mensuales, dtype: float64

In [106]:
# Creamos una columna con el tiempo que lleva siendo cliente hasta la interaccion en meses

df['tiempo_cliente'] = (df['fecha_interaccion'] - df['fecha_alta_cliente']).dt.days // 30

In [107]:
df['tiempo_cliente'].value_counts()

tiempo_cliente
56.0    732
42.0    726
43.0    723
59.0    721
55.0    719
       ...
95.0     44
1.0      34
96.0     27
0.0       7
97.0      2
Name: count, Length: 98, dtype: int64

In [108]:
df['tiempo_cliente'].describe()

count    42752.000000
mean        49.907256
std         20.991747
min          0.000000
25%         34.000000
50%         50.000000
75%         66.000000
max         97.000000
Name: tiempo_cliente, dtype: float64

In [109]:
# los segmentamos por nuevo, reciente y antiguo

def segmentacion_clientes(meses):
    if meses < 6 :
        return 'nuevo'
    elif meses < 24:
        return 'reciente'
    else:
        return 'antiguo'
    
df['antiguedad_cliente'] = df['tiempo_cliente'].apply(segmentacion_clientes)

In [110]:
df['antiguedad_cliente'].value_counts()

antiguedad_cliente
antiguo     37976
reciente     4671
nuevo         353
Name: count, dtype: int64

In [111]:
# Creamos la columna mes de interaccion

df['mes_interaccion'] = df['fecha_interaccion'].dt.month

In [112]:
df['mes_interaccion'].value_counts()

mes_interaccion
11.0    3603
10.0    3599
7.0     3593
3.0     3589
4.0     3582
2.0     3577
9.0     3569
5.0     3547
6.0     3538
8.0     3526
1.0     3517
12.0    3512
Name: count, dtype: int64

In [113]:
mes_año = {1 : 'enero',
           2 : 'febrero',
           3 : 'marzo',
           4 : 'abril',
           5 : 'mayo',
           6 : 'junio',
           7 : 'julio',
           8 : 'agosto',
           9 : 'septiembre',
           10 : 'octubre',
           11 : 'noviembre',
           12 : 'diciembre'}

In [114]:
df['mes_interaccion'] = df['mes_interaccion'].map(mes_año)

In [115]:
df['mes_interaccion'].value_counts()

mes_interaccion
noviembre     3603
octubre       3599
julio         3593
marzo         3589
abril         3582
febrero       3577
septiembre    3569
mayo          3547
junio         3538
agosto        3526
enero         3517
diciembre     3512
Name: count, dtype: int64

In [116]:
# y el dia de la interaccion

df['dia_interaccion'] = df['fecha_interaccion'].dt.day_of_week

In [117]:
df['dia_interaccion'].value_counts()

dia_interaccion
4.0    6212
3.0    6198
6.0    6149
5.0    6147
0.0    6035
1.0    6032
2.0    5979
Name: count, dtype: int64

In [118]:
dias_semana = {0 : 'lunes',
               1 : 'martes',
               2 : 'miercoles',
               3 : 'jueves',
               4 : 'viernes',
               5 : 'sabado',
               6 : 'domingo'}

In [119]:
df['dia_interaccion'] = df['dia_interaccion'].map(dias_semana)

In [120]:
df['dia_interaccion'].value_counts()

dia_interaccion
viernes      6212
jueves       6198
domingo      6149
sabado       6147
lunes        6035
martes       6032
miercoles    5979
Name: count, dtype: int64

In [121]:
# Asi queda el data set limpio y preparado para el EDA

df.head()

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales,num_hijos,tiempo_cliente,antiguedad_cliente,mes_interaccion,dia_interaccion
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,False,False,telephone,261,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2019-08-02,161770,1,0,2012-04-04,29,1,89.0,antiguo,agosto,viernes
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,False,False,telephone,149,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2016-09-14,85477,1,1,2012-12-30,7,2,45.0,antiguo,septiembre,miercoles
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,True,False,telephone,226,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2019-02-15,147233,1,1,2012-02-02,5,2,85.0,antiguo,febrero,viernes
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,False,False,telephone,151,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2015-11-29,121393,1,2,2012-12-21,29,3,35.0,antiguo,noviembre,domingo
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,False,True,telephone,307,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2017-01-29,63164,1,2,2012-06-20,20,3,56.0,antiguo,enero,domingo

In [122]:
df.isna().sum()

edad                            5120
ocupacion                        345
estado_civil                      85
nivel_educativo                 1807
prestamo_hipotecario            1026
otro_prestamo                   1026
metodo_contacto                    0
duracion_ultima_interaccion        0
contactos_en_campaña               0
dias_ultimo_contacto           41412
contactos_previos                  0
resultado_campaña_previa       37103
tasa_variacion_empleo              0
indice_precios_consumidor        471
indice_confianza_consumidor        0
tasa_interes_3m                 9256
numero_empleados                   0
suscripcion_producto               0
fecha_interaccion                248
ingreso_anual                      0
num_niños                          0
num_adolescentes                   0
fecha_alta_cliente                 0
visitas_web_mensuales              0
num_hijos                          0
tiempo_cliente                   248
antiguedad_cliente                 0
mes_interaccion                  248
dia_interaccion                  248
dtype: int64

In [123]:
df.dtypes

edad                                  float64
ocupacion                                 str
estado_civil                              str
nivel_educativo                           str
prestamo_hipotecario                   object
otro_prestamo                          object
metodo_contacto                           str
duracion_ultima_interaccion             int64
contactos_en_campaña                    int64
dias_ultimo_contacto                  float64
contactos_previos                       int64
resultado_campaña_previa               object
tasa_variacion_empleo                 float64
indice_precios_consumidor             float64
indice_confianza_consumidor           float64
tasa_interes_3m                       float64
numero_empleados                      float64
suscripcion_producto                     bool
fecha_interaccion              datetime64[us]
ingreso_anual                           int64
num_niños                               int64
num_adolescentes                        int64
fecha_alta_cliente             datetime64[us]
visitas_web_mensuales                   int64
num_hijos                               int64
tiempo_cliente                        float64
antiguedad_cliente                        str
mes_interaccion                           str
dia_interaccion                           str
dtype: object

In [124]:
df.to_pickle('dataframe_limpio.pkl')

In [125]:
df.to_csv('dataframe_limpio.csv')